export const consistencia = [
  {
    iD: 1,
    nombre: "EFREN AVILA",
    quinielaiela: 1,
    resultados: 0,
    survivor: true,
    existe: 0,
  },
  {
    iD: 2,
    nombre: "LUIS O. ALVAREZ",
    quiniela: 1,
    resultados: 0,
    survivor: true,
    existe: 1,
  },
  {
    iD: 3,
    nombre: "DUSTIN CRUZ",
    quiniela: 1,
    resultados: 0,
    survivor: false,
    existe: 0,
  },
  {
    iD: 4,
    nombre: "KAREN PEREZ",
    quiniela: 1,
    resultados: 0,
    survivor: false,
    existe: 0,
  },
  {
    iD: 5,
    nombre: "GUSTAVO SOLIS",
    quiniela: 1,
    resultados: 0,
    survivor: false,
    existe: 0,
  },
  {
    iD: 6,
    nombre: "HECTOR ALVAREZ",
    quiniela: 1,
    resultados: 0,
    survivor: false,
    existe: 1,
  },
  {
    iD: 7,
    nombre: "JONATAN PARRA",
    quiniela: 1,
    resultados: 0,
    survivor: false,
    existe: 0,
  },
  {
    iD: 8,
    nombre: "MARIO LOPEZ",
    quiniela: 0,
    resultados: 1,
    survivor: false,
    existe: 0,
  },
  {
    iD: 9,
    nombre: "NATALIA CASTILLO",
    quiniela: 1,
    resultados: 0,
    survivor: false,
    existe: 1,
  },
  {
    iD: 10,
    nombre: "ALEJANDRO ORTEGA",
    quiniela: 1,
    resultados: 1,
    survivor: false,
    existe: 0,
  },
  {
    iD: 11,
    nombre: "PEDRO CANEDO",
    quiniela: 1,
    resultados: 0,
    survivor: false,
    existe: 0,
  },
  {
    iD: 12,
    nombre: "DIEGO OJEDA",
    quiniela: 1,
    resultados: 0,
    survivor: false,
    existe: 0,
  },
  {
    iD: 13,
    nombre: "DAVID ALVARADO",
    quiniela: 1,
    resultados: 1,
    survivor: false,
    existe: 0,
  },
  {
    iD: 14,
    nombre: "HUMBERTO LOPEZ",
    quiniela: 1,
    resultados: 0,
    survivor: false,
    existe: 0,
  },
];
