export const formData1 = {
  infoForma: {
    cveAplicacion: "PRUEBA",
    cve_forma: "fPrueba",
    cveTituloForma: "fPruebaTit",
    txTituloForma: "PANTALLA DE PRUEBA",
    urlApiForma: "http://localhost:3000/api/v1/gridData",
    descForma: "Pantalla de prueba para la captura de clientes",
    endpoint: "gridData",
    cveTipoForma: "VENTANA",
    cveTipoLayout: "AUTO",
    numColumnas: 0,
    bGrid: true,
    fFiltra: true,
    bReporta: true,
    bCrea: true,
    bEdita: true,
    bBorra: true,
    cveCategoria: "CATALOGO",
    nomTablaDb: "IN_PRUEBA",
    fnAcepta: "validaForma",
  },
  infComponente: [
    {
      nomComponente: "numCliente",
      cveTipoCampo: "number",
      cveTipoCompon: "NUMERO",
      bCampoBd: true,
      nomCampoBd: "NUM_CLIENTE",
      numOrden: 1,
      numFila: 2,
      numColumna: 1,
      cveEtiqueta: "ENUMCTE",
      txEtiqueta: "Num. Cliente",
      cveAyuda: "ANUMCTE",
      txAyuda: "Numero de cliente unico",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: true,
      bFiltra: true,
      bReporta: true,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: null,
    },
    {
      nomComponente: "nomCliente",
      cveTipoCampo: "string",
      cveTipoCompon: "TEXTO",
      bCampoBd: true,
      nomCampoBd: "NOMBRE_CLIENTE",
      numOrden: 2,
      numFila: 1,
      numColumna: 1,
      cveEtiqueta: "ENOMCTE",
      txEtiqueta: "Nombre Cliente",
      cveAyuda: "ANOMCTE",
      txAyuda: "Nombre, Apellido Paterno, Apellido Materno",
      bCrea: true,
      bEdita: true,
      bRequerido: false,
      bGrid: true,
      bFiltra: true,
      bReporta: true,
      fnValida: "fnValNombre",
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        CVE_APLICACION: "PRUEBA",
        CVE_FORMA: "fPrueba",
        NOM_COMPONENTE: "nomCliente",
        VALOR_INICIAL: "0",
        NUM_LONG_MIN: 1,
        NUM_LONG_MAX: 50,
        NUM_ENTEROS: 0,
        NUM_DECIMALES: 0,
        TX_REG_EXP: "\\/^[A-Za-z]+$\\/",
      },
    },
    /* {
      nomComponente: "tipoCliente",
      cveTipoCampo: "string",
      cveTipoCompon: "COMBO",
      bCampoBd: true,
      nomCampoBd: "TIPO_CLIENTE",
      numOrden: 3,
      numFila: 3,
      numColumna: 1,
      endpoint: "comboData",
      cveEtiqueta: "ETIPOCTE",
      txEtiqueta: "Tipo Cliente",
      cveAyuda: "ATIPOCTE",
      txAyuda: "El tipo de cliente asignado a su perfil",
      key: "descripcion",
      value: "clave",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: true,
      bFiltra: true,
      bReporta: true,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        CVE_APLICACION: "PRUEBA",
        CVE_FORMA: "fPrueba",
        NOM_COMPONENTE: "tipoCliente",
        NOM_CAMPO_VALOR: "cveTipoCte",
        NOM_CAMPO_ETIQUETA: "tipoCliente",
        FN_OBT_VALOR: null,
      },
    }, */
    {
      nomComponente: "infSalarial",
      cveTipoCampo: null,
      cveTipoCompon: "SEPARADOR",
      bCampoBd: false,
      nomCampoBd: null,
      numOrden: 4,
      numFila: 4,
      numColumna: 1,
      cveEtiqueta: null,
      txEtiqueta: null,
      cveAyuda: null,
      txAyuda: null,
      bCrea: false,
      bEdita: false,
      bRequerido: false,
      bGrid: false,
      bFiltra: false,
      bReporta: false,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        CVE_APLICACION: "PRUEBA",
        CVE_FORMA: "fPrueba",
        NOM_COMPONENTE: "infSalarial",
        ICONO_CLS: null,
      },
    },
    {
      nomComponente: "impSueldo",
      cveTipoCampo: "numeric",
      cveTipoCompon: "NUMERO",
      bCampoBd: true,
      nomCampoBd: "IMP_SUELDO",
      numOrden: 5,
      numFila: 1,
      numColumna: 1,
      cveEtiqueta: "ESUELDO",
      txEtiqueta: "Sueldo",
      cveAyuda: "ASUELDO",
      txAyuda: "Sueldo que percibe el cliente",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: true,
      bFiltra: false,
      bReporta: true,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        CVE_APLICACION: "PRUEBA",
        CVE_FORMA: "fPrueba",
        NOM_COMPONENTE: "impSueldo",
        VALOR_INICIAL: "0",
        NUM_LONG_MIN: 0,
        NUM_LONG_MAX: 0,
        NUM_ENTEROS: 16,
        NUM_DECIMALES: 0,
        TX_REG_EXP: null,
      },
    },
    {
      nomComponente: "impSobreSueldo",
      cveTipoCampo: "numeric",
      cveTipoCompon: "NUMERO",
      bCampoBd: true,
      nomCampoBd: "IMP_SOBRE_SUELDO",
      numOrden: 6,
      numFila: 1,
      numColumna: 1,
      cveEtiqueta: "ESSUELDO",
      txEtiqueta: "Sobre Sueldo",
      cveAyuda: "ASSUELDO",
      txAyuda: "Sobre Sueldo que percibe el cliente",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: false,
      bFiltra: false,
      bReporta: true,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        CVE_APLICACION: "PRUEBA",
        CVE_FORMA: "fPrueba",
        NOM_COMPONENTE: "impSobreSueldo",
        VALOR_INICIAL: "0",
        NUM_LONG_MIN: 0,
        NUM_LONG_MAX: 0,
        NUM_ENTEROS: 16,
        NUM_DECIMALES: 0,
        TX_REG_EXP: null,
      },
    },
    {
      nomComponente: "total",
      cveTipoCampo: "numeric",
      cveTipoCompon: "NUMERO",
      bCampoBd: false,
      nomCampoBd: null,
      numOrden: 7,
      numFila: 1,
      numColumna: 1,
      cveEtiqueta: "ATOTAL",
      txEtiqueta: "Total",
      cveAyuda: "ATOTAL",
      txAyuda: "Sueldo + Sobresueldo",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: false,
      bFiltra: false,
      bReporta: true,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: "fnObtTotal",
      infdetComp: {
        CVE_APLICACION: "PRUEBA",
        CVE_FORMA: "fPrueba",
        NOM_COMPONENTE: "total",
        VALOR_INICIAL: "0",
        NUM_LONG_MIN: 6,
        NUM_LONG_MAX: 16,
        NUM_ENTEROS: 2,
        NUM_DECIMALES: 0,
        TX_REG_EXP: null,
      },
    },
    {
      nomComponente: "separa",
      cveTipoCampo: null,
      cveTipoCompon: "SEPARADOR",
      bCampoBd: false,
      nomCampoBd: null,
      numOrden: 8,
      numFila: 4,
      numColumna: 1,
      cveEtiqueta: null,
      txEtiqueta: null,
      cveAyuda: null,
      txAyuda: null,
      bCrea: false,
      bEdita: false,
      bRequerido: false,
      bGrid: false,
      bFiltra: false,
      bReporta: false,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        CVE_APLICACION: "PRUEBA",
        CVE_FORMA: "fPrueba",
        NOM_COMPONENTE: "separa",
        ICONO_CLS: null,
      },
    },
    {
      nomComponente: "fIngreso",
      cveTipoCampo: "date",
      cveTipoCompon: "FECHA",
      bCampoBd: true,
      nomCampoBd: "F_INGRESO",
      numOrden: 9,
      numFila: 1,
      numColumna: 1,
      cveEtiqueta: "EFINGRESO",
      txEtiqueta: "Fecha Ingreso",
      cveAyuda: "AFINGRESO",
      txAyuda: "Fecha en la que ingreso el cliente",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: true,
      bFiltra: false,
      bReporta: true,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: null,
    },
    {
      nomComponente: "descripcion",
      cveTipoCampo: "string",
      cveTipoCompon: "AREA",
      bCampoBd: true,
      nomCampoBd: "DESCRIPCION",
      numOrden: 10,
      numFila: 1,
      numColumna: 1,
      cveEtiqueta: "EDESCRIP",
      txEtiqueta: "Descripción",
      cveAyuda: "ADESCRIP",
      txAyuda: "Descripcion del perfil del Cliente",
      bCrea: true,
      bEdita: true,
      bRequerido: false,
      bGrid: false,
      bFiltra: false,
      bReporta: true,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        CVE_APLICACION: "PRUEBA",
        CVE_FORMA: "fPrueba",
        NOM_COMPONENTE: "descripcion",
        VALOR_INICIAL: "1",
        NUM_LONG_MIN: 0,
        NUM_LONG_MAX: 100,
        NUM_ENTEROS: 0,
        NUM_DECIMALES: 0,
        TX_REG_EXP: null,
      },
    },
    {
      nomComponente: "bActivo",
      cveTipoCampo: "bit",
      cveTipoCompon: "SWITCH",
      bCampoBd: true,
      nomCampoBd: "B_ACTIVO",
      numOrden: 11,
      numFila: 1,
      numColumna: 1,
      cveEtiqueta: null,
      txEtiqueta: "Activo",
      cveAyuda: null,
      txAyuda: null,
      bCrea: true,
      bEdita: true,
      bRequerido: false,
      bGrid: false,
      bFiltra: false,
      bReporta: true,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: null,
    },
  ],
};

export const formData2 = {
  infoForma: {
    cveAplicacion: "QUINIELA",
    cve_forma: "fQuiniela",
    cveTituloForma: "fQuinielaTit",
    txTituloForma: "Formulario de Quiniela",
    urlApiForma: "http://localhost:3000/api/v1/quinielaData",
    descForma: "Captura de predicciones para partidos de fútbol",
    endpoint: "quinielaData",
    cveTipoForma: "VENTANA",
    cveTipoLayout: "AUTO",
    numColumnas: 1,
    bGrid: true,
    fFiltra: false,
    bReporta: true,
    bCrea: true,
    bEdita: true,
    bBorra: false,
    cveCategoria: "JUEGO",
    nomTablaDb: "QN_PARTICIPACION",
    fnAcepta: "validaQuiniela",
  },
  infComponente: [
    {
      nomComponente: "nombreParticipante",
      cveTipoCampo: "string",
      cveTipoCompon: "TEXTO",
      bCampoBd: true,
      nomCampoBd: "NOMBRE_PARTICIPANTE",
      numOrden: 1,
      numFila: 1,
      numColumna: 1,
      cveEtiqueta: "ENOMBRE",
      txEtiqueta: "Nombre del Participante",
      cveAyuda: "ANOMBRE",
      txAyuda: "Nombre completo del participante",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: true,
      bFiltra: false,
      bReporta: true,
      fnValida: null,
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        VALOR_INICIAL: "",
        NUM_LONG_MIN: 3,
        NUM_LONG_MAX: 100,
        TX_REG_EXP: "^[A-Za-zÁÉÍÓÚÑáéíóúñ ]+$",
      },
    },
    {
      nomComponente: "partido1",
      cveTipoCampo: "string",
      cveTipoCompon: "TEXTO",
      bCampoBd: true,
      nomCampoBd: "RESULTADO_P1",
      numOrden: 2,
      numFila: 2,
      numColumna: 1,
      cveEtiqueta: "EPARTIDO1",
      txEtiqueta: "Partido 1 (A vs B)",
      cveAyuda: "APARTIDO1",
      txAyuda: "Escribe L, E o V",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: true,
      bFiltra: false,
      bReporta: true,
      fnValida: "fnValResultado",
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        VALOR_INICIAL: "",
        NUM_LONG_MIN: 1,
        NUM_LONG_MAX: 1,
        TX_REG_EXP: "^[LEVlev]$",
      },
    },
    {
      nomComponente: "partido2",
      cveTipoCampo: "string",
      cveTipoCompon: "TEXTO",
      bCampoBd: true,
      nomCampoBd: "RESULTADO_P2",
      numOrden: 3,
      numFila: 3,
      numColumna: 1,
      cveEtiqueta: "EPARTIDO2",
      txEtiqueta: "Partido 2 (C vs D)",
      cveAyuda: "APARTIDO2",
      txAyuda: "Escribe L, E o V",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: true,
      bFiltra: false,
      bReporta: true,
      fnValida: "fnValResultado",
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        VALOR_INICIAL: "",
        NUM_LONG_MIN: 1,
        NUM_LONG_MAX: 1,
        TX_REG_EXP: "^[LEVlev]$",
      },
    },
    {
      nomComponente: "partido3",
      cveTipoCampo: "string",
      cveTipoCompon: "TEXTO",
      bCampoBd: true,
      nomCampoBd: "RESULTADO_P3",
      numOrden: 4,
      numFila: 4,
      numColumna: 1,
      cveEtiqueta: "EPARTIDO3",
      txEtiqueta: "Partido 3 (E vs F)",
      cveAyuda: "APARTIDO3",
      txAyuda: "Escribe L, E o V",
      bCrea: true,
      bEdita: true,
      bRequerido: true,
      bGrid: true,
      bFiltra: false,
      bReporta: true,
      fnValida: "fnValResultado",
      fnMuestra: null,
      fnObtValor: null,
      infdetComp: {
        VALOR_INICIAL: "",
        NUM_LONG_MIN: 1,
        NUM_LONG_MAX: 1,
        TX_REG_EXP: "^[LEVlev]$",
      },
    },
  ],
};
