export const gridData1 = [
  {
    numCliente: 1,
    nomCliente: "Adam James",
    tipoCliente: "CO",
    impSueldo: 1233,
    fIngreso: "2021-04-22",
  },
  {
    numCliente: 2,
    nomCliente: "Paisley Sanchez",
    tipoCliente: "TM",
    impSueldo: 1233,
    fIngreso: "2023-11-09",
  },
  {
    numCliente: 3,
    nomCliente: "Timothy Price",
    tipoCliente: "CO",
    impSueldo: 1233,
    fIngreso: "2020-09-03",
  },
  {
    numCliente: 4,
    nomCliente: "Ellie Myers",
    tipoCliente: "HO",
    impSueldo: 1233,
    fIngreso: "2024-06-18",
  },
  {
    numCliente: 5,
    nomCliente: "Aaron Bennett",
    tipoCliente: "CO",
    impSueldo: 1233,
    fIngreso: "2021-01-12",
  },
  {
    numCliente: 6,
    nomCliente: "Hazel Richardson",
    tipoCliente: "TM",
    impSueldo: 1233,
    fIngreso: "2025-02-05",
  },
  {
    numCliente: 7,
    nomCliente: "Jose Wood",
    tipoCliente: "CO",
    impSueldo: 1233,
    fIngreso: "2023-05-27",
  },
  {
    numCliente: 8,
    nomCliente: "Violet Watson",
    tipoCliente: "TM",
    impSueldo: 1233,
    fIngreso: "2020-12-19",
  },
  {
    numCliente: 9,
    nomCliente: "Larry Brooks",
    tipoCliente: "CO",
    impSueldo: 1233,
    fIngreso: "2024-01-30",
  },
  {
    numCliente: 10,
    nomCliente: "Luna Kelly",
    tipoCliente: "TM",
    impSueldo: 1233,
    fIngreso: "2022-03-08",
  },
  {
    numCliente: 11,
    nomCliente: "Scott Sanders",
    tipoCliente: "CO",
    impSueldo: 1233,
    fIngreso: "2021-07-14",
  },
  {
    numCliente: 12,
    nomCliente: "Aurora Reed",
    tipoCliente: "HO",
    impSueldo: 1233,
    fIngreso: "2023-09-21",
  },
  {
    numCliente: 13,
    nomCliente: "Eric Murphy",
    tipoCliente: "CO",
    impSueldo: 1233,
    fIngreso: "2020-06-05",
  },
  {
    numCliente: 14,
    nomCliente: "Savannah Barnes",
    tipoCliente: "TM",
    fIngreso: "2024-10-26",
  },
  {
    numCliente: 15,
    nomCliente: "Frank Powell",
    tipoCliente: "CO",
    fIngreso: "2021-09-28",
  },
  {
    numCliente: 16,
    nomCliente: "Claire Perry",
    tipoCliente: "TM",
    fIngreso: "2023-02-17",
  },
  {
    numCliente: 17,
    nomCliente: "Raymond Ross",
    tipoCliente: "CO",
    fIngreso: "2025-01-11",
  },
  {
    numCliente: 18,
    nomCliente: "Maya Foster",
    tipoCliente: "TM",
    fIngreso: "2022-11-23",
  },
  {
    numCliente: 19,
    nomCliente: "Patrick Jenkins",
    tipoCliente: "CO",
    fIngreso: "2020-03-10",
  },
  {
    numCliente: 20,
    nomCliente: "Lucy Butler",
    tipoCliente: "HO",
    fIngreso: "2024-04-01",
  },
  {
    numCliente: 21,
    nomCliente: "Harold Cox",
    tipoCliente: "CO",
    fIngreso: "2021-06-03",
  },
  {
    numCliente: 22,
    nomCliente: "Sadie Simmons",
    tipoCliente: "TM",
    fIngreso: "2023-07-29",
  },
  {
    numCliente: 23,
    nomCliente: "Walter Bailey",
    tipoCliente: "CO",
    fIngreso: "2020-11-16",
  },
  {
    numCliente: 24,
    nomCliente: "Madelyn Hayes",
    tipoCliente: "TM",
    fIngreso: "2024-12-07",
  },
  {
    numCliente: 25,
    nomCliente: "Dennis Torres",
    tipoCliente: "CO",
    fIngreso: "2022-01-27",
  },
  {
    numCliente: 26,
    nomCliente: "Allison Bryant",
    tipoCliente: "TM",
    fIngreso: "2021-08-19",
  },
  {
    numCliente: 27,
    nomCliente: "Roger Alexander",
    tipoCliente: "CO",
    fIngreso: "2023-04-05",
  },
  {
    numCliente: 28,
    nomCliente: "Caroline Russell",
    tipoCliente: "HO",
    fIngreso: "2020-05-12",
  },
  {
    numCliente: 29,
    nomCliente: "Albert Griffin",
    tipoCliente: "CO",
    fIngreso: "2024-08-20",
  },
  {
    numCliente: 30,
    nomCliente: "Ruby Stewart",
    tipoCliente: "TM",
    fIngreso: "2022-06-14",
  },
  {
    numCliente: 31,
    nomCliente: "Jerry Chapman",
    tipoCliente: "CO",
    fIngreso: "2021-10-31",
  },
  {
    numCliente: 32,
    nomCliente: "Ivy Flores",
    tipoCliente: "TM",
    fIngreso: "2023-01-08",
  },
  {
    numCliente: 33,
    nomCliente: "Carl Medina",
    tipoCliente: "CO",
    fIngreso: "2020-02-07",
  },
  {
    numCliente: 34,
    nomCliente: "Delilah Ruiz",
    tipoCliente: "TM",
    fIngreso: "2024-03-24",
  },
  {
    numCliente: 35,
    nomCliente: "Ralph Gomez",
    tipoCliente: "CO",
    fIngreso: "2022-09-26",
  },
  {
    numCliente: 36,
    nomCliente: "Naomi Gutierrez",
    tipoCliente: "HO",
    fIngreso: "2021-03-18",
  },
  {
    numCliente: 37,
    nomCliente: "Howard Moreno",
    tipoCliente: "CO",
    fIngreso: "2023-12-15",
  },
  {
    numCliente: 38,
    nomCliente: "Elena Porter",
    tipoCliente: "TM",
    fIngreso: "2020-07-23",
  },
  {
    numCliente: 39,
    nomCliente: "Roy Reyes",
    tipoCliente: "CO",
    fIngreso: "2024-07-02",
  },
  {
    numCliente: 40,
    nomCliente: "Leah Wright",
    tipoCliente: "TM",
    fIngreso: "2022-05-01",
  },
  {
    numCliente: 41,
    nomCliente: "Earl Lopez",
    tipoCliente: "CO",
    fIngreso: "2021-12-06",
  },
  {
    numCliente: 42,
    nomCliente: "Willow Young",
    tipoCliente: "TM",
    fIngreso: "2023-08-11",
  },
  {
    numCliente: 43,
    nomCliente: "Eugene Gonzalez",
    tipoCliente: "CO",
    fIngreso: "2020-04-28",
  },
  {
    numCliente: 44,
    nomCliente: "Kinsley Perez",
    tipoCliente: "HO",
    fIngreso: "2024-11-19",
  },
  {
    numCliente: 45,
    nomCliente: "Lawrence Clark",
    tipoCliente: "CO",
    fIngreso: "2022-02-11",
  },
  {
    numCliente: 46,
    nomCliente: "Nova Rivera",
    tipoCliente: "TM",
    fIngreso: "2021-09-05",
  },
  {
    numCliente: 47,
    nomCliente: "Martin Hill",
    tipoCliente: "CO",
    fIngreso: "2023-06-20",
  },
  {
    numCliente: 48,
    nomCliente: "Iris Mitchell",
    tipoCliente: "CO",
    fIngreso: "2020-08-30",
  },
  {
    numCliente: 49,
    nomCliente: "Addison Cox",
    tipoCliente: "TM",
    fIngreso: "2024-02-14",
  },
  {
    numCliente: 50,
    nomCliente: "Jonathan Gray",
    tipoCliente: "CO",
    fIngreso: "2022-07-07",
  },
  {
    numCliente: 51,
    nomCliente: "Stella Ramirez",
    tipoCliente: "TM",
    fIngreso: "2021-05-17",
  },
  {
    numCliente: 52,
    nomCliente: "Adam James",
    tipoCliente: "CO",
    fIngreso: "2023-10-23",
  },
  {
    numCliente: 53,
    nomCliente: "Paisley Sanchez",
    tipoCliente: "HO",
    fIngreso: "2020-01-15",
  },
  {
    numCliente: 54,
    nomCliente: "Timothy Price",
    tipoCliente: "CO",
    fIngreso: "2024-05-09",
  },
  {
    numCliente: 55,
    nomCliente: "Ellie Myers",
    tipoCliente: "TM",
    fIngreso: "2022-10-18",
  },
  {
    numCliente: 56,
    nomCliente: "Aaron Bennett",
    tipoCliente: "CO",
    fIngreso: "2021-02-28",
  },
  {
    numCliente: 57,
    nomCliente: "Hazel Richardson",
    tipoCliente: "CO",
    fIngreso: "2023-05-03",
  },
  {
    numCliente: 58,
    nomCliente: "Jose Wood",
    tipoCliente: "CO",
    fIngreso: "2024-06-11",
  },
  {
    numCliente: 59,
    nomCliente: "Violet Watson",
    tipoCliente: "HO",
    fIngreso: "2020-12-03",
  },
  {
    numCliente: 60,
    nomCliente: "Larry Brooks",
    tipoCliente: "CO",
    fIngreso: "2021-09-01",
  },
];

export const gridData2 = [
  {
    nombreParticipante: "Carlos Ramírez",
    partido1: "L",
    partido2: "V",
    partido3: "E",
  },
  {
    nombreParticipante: "Mariana Torres",
    partido1: "E",
    partido2: "E",
    partido3: "L",
  },
  {
    nombreParticipante: "José Martínez",
    partido1: "V",
    partido2: "L",
    partido3: "V",
  },
  {
    nombreParticipante: "Laura Gutiérrez",
    partido1: "L",
    partido2: "L",
    partido3: "L",
  },
  {
    nombreParticipante: "Andrés López",
    partido1: "E",
    partido2: "V",
    partido3: "L",
  },
  {
    nombreParticipante: "Ana Fernández",
    partido1: "L",
    partido2: "E",
    partido3: "V",
  },
  {
    nombreParticipante: "Diego Soto",
    partido1: "V",
    partido2: "E",
    partido3: "E",
  },
  {
    nombreParticipante: "Paola Díaz",
    partido1: "L",
    partido2: "L",
    partido3: "V",
  },
  {
    nombreParticipante: "Luis Morales",
    partido1: "E",
    partido2: "L",
    partido3: "E",
  },
  {
    nombreParticipante: "Sandra Vega",
    partido1: "V",
    partido2: "V",
    partido3: "L",
  },
  {
    nombreParticipante: "Raúl Ortega",
    partido1: "L",
    partido2: "E",
    partido3: "E",
  },
  {
    nombreParticipante: "Lucía Méndez",
    partido1: "E",
    partido2: "V",
    partido3: "V",
  },
  {
    nombreParticipante: "Fernando Ríos",
    partido1: "V",
    partido2: "L",
    partido3: "E",
  },
  {
    nombreParticipante: "Gabriela Navarro",
    partido1: "E",
    partido2: "E",
    partido3: "E",
  },
  {
    nombreParticipante: "Ricardo Castañeda",
    partido1: "L",
    partido2: "V",
    partido3: "L",
  },
  {
    nombreParticipante: "Diana Salinas",
    partido1: "V",
    partido2: "E",
    partido3: "L",
  },
  {
    nombreParticipante: "Hugo Herrera",
    partido1: "E",
    partido2: "L",
    partido3: "V",
  },
  {
    nombreParticipante: "Alejandra Cruz",
    partido1: "L",
    partido2: "L",
    partido3: "E",
  },
  {
    nombreParticipante: "Bruno Nieto",
    partido1: "V",
    partido2: "V",
    partido3: "V",
  },
  {
    nombreParticipante: "Camila Robles",
    partido1: "E",
    partido2: "E",
    partido3: "L",
  },
  {
    nombreParticipante: "Pablo Mendoza",
    partido1: "L",
    partido2: "E",
    partido3: "E",
  },
  {
    nombreParticipante: "Natalia Reyes",
    partido1: "E",
    partido2: "L",
    partido3: "L",
  },
  {
    nombreParticipante: "Iván Salgado",
    partido1: "V",
    partido2: "L",
    partido3: "E",
  },
  {
    nombreParticipante: "Renata Domínguez",
    partido1: "L",
    partido2: "V",
    partido3: "V",
  },
  {
    nombreParticipante: "Marco Paredes",
    partido1: "E",
    partido2: "L",
    partido3: "V",
  },
  {
    nombreParticipante: "Valeria Peña",
    partido1: "V",
    partido2: "E",
    partido3: "L",
  },
  {
    nombreParticipante: "Esteban Carrillo",
    partido1: "L",
    partido2: "V",
    partido3: "E",
  },
  {
    nombreParticipante: "Sofía Acosta",
    partido1: "E",
    partido2: "E",
    partido3: "E",
  },
  {
    nombreParticipante: "Emilio Bravo",
    partido1: "V",
    partido2: "V",
    partido3: "L",
  },
  {
    nombreParticipante: "Julia Cortés",
    partido1: "L",
    partido2: "L",
    partido3: "V",
  },
];
