export const menu = {
  active: false,
  aplicacion: "App1",
  bHoja: false,
  children: [
    {
      active: false,
      aplicacion: "App1",
      bHoja: true,
      cveAplicacion: "App1",
      cveMenu: "dashboard",
      cveMenuP: "root",
      descMenu: "Dashboard",
      icono: "check",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "/dashboard",
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: true,
      cveAplicacion: "App1",
      cveMenu: "matches",
      cveMenuP: "root",
      descMenu: "Captura de Quinielas",
      icono: "gamepad-2",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "/matches",
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "formas",
      cveMenuP: "root",
      descMenu: "Posiciones",
      icono: "file-question-mark",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "/participantStandings",
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "quiniela",
      cveMenuP: "root",
      descMenu: "Survivor",
      icono: "trophy",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "",
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "survivor",
      cveMenuP: "root",
      descMenu: "Activa Survivor",
      icono: "swords",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "/survivor",
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "marcadores",
      cveMenuP: "root",
      descMenu: "Resultados",
      icono: "list-ordered",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "",
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "settings",
      cveMenuP: "root",
      descMenu: "Bolsa Acumulada",
      icono: "cog",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "",
    },
  ],
  cveAplicacion: "App1",
  cveMenu: "root",
  cveMenuP: "",
  descMenu: "Main Menu",
  icono: "bars",
  menuPadre: "",
  numNivel: 0,
  urlMenu: "",
};
