export const menu = [
  {
    active: false,
    bHoja: false,
    cveAplicacion: "NFL",
    cveMenu: "root",
    cveMenuP: null,
    descMenu: "Menu Principal",
    icono: null,
    numNivel: 0,
    urlMenu: null,
    children: [
      {
        active: false,
        bHoja: true,
        cveAplicacion: "NFL",
        cveMenu: "F_CON_MARCADORES",
        cveMenuP: "root",
        descMenu: "Consulta de Marcadores",
        icono: "file-digit",
        numNivel: 1,
        urlMenu: "/markerQuery",
        children: null,
      },
      {
        active: false,
        bHoja: true,
        cveAplicacion: "NFL",
        cveMenu: "F_CAP_QUINIELA",
        cveMenuP: "root",
        descMenu: "Captura de Quinielas",
        icono: "square-pen",
        numNivel: 1,
        urlMenu: "/quinielaCapture",
        children: null,
      },
      {
        active: false,
        bHoja: true,
        cveAplicacion: "NFL",
        cveMenu: "F_CON_POSICIONES",
        cveMenuP: "root",
        descMenu: "Consulta de Posiciones",
        icono: "list-ordered",
        numNivel: 1,
        urlMenu: "/positionQuery",
        children: null,
      },
      {
        active: false,
        bHoja: true,
        cveAplicacion: "NFL",
        cveMenu: "F_CON_PRINCIPAL",
        cveMenuP: "root",
        descMenu: "Panel Principal",
        icono: "layout-dashboard",
        numNivel: 1,
        urlMenu: "/dashboard",
        children: null,
      },
      {
        active: false,
        bHoja: true,
        cveAplicacion: "NFL",
        cveMenu: "F_CON_SURVIVOR",
        cveMenuP: "root",
        descMenu: "Consulta de Survivor",
        icono: "swords",
        numNivel: 1,
        urlMenu: "/survivorQuery",
        children: null,
      },
      {
        active: false,
        bHoja: false,
        cveAplicacion: "NFL",
        cveMenu: "MN_CAPTURAS",
        cveMenuP: "root",
        descMenu: "Menu Capturas",
        icono: "notebook-tabs",
        numNivel: 1,
        urlMenu: "",
        children: [
          {
            active: false,
            aplicacion: "NFL",
            bHoja: true,
            cveAplicacion: "NFL",
            cveMenu: "F_CAP_MARCADORES",
            cveMenuP: "MN_CAPTURAS",
            descMenu: "Captura de Marcadores",
            icono: "notebook-pen",
            numNivel: 2,
            urlMenu: "/captures/markerCapture",
          },
          {
            active: false,
            aplicacion: "NFL",
            bHoja: true,
            cveAplicacion: "NFL",
            cveMenu: "F_CAP_PAGO_SURV",
            cveMenuP: "MN_CAPTURAS",
            descMenu: "Pago de Survivor",
            icono: "hand-coins",
            numNivel: 2,
            urlMenu: "/captures/survivorPayment",
          },
          {
            active: false,
            aplicacion: "NFL",
            bHoja: true,
            cveAplicacion: "NFL",
            cveMenu: "F_CAP_SURVIVOR",
            cveMenuP: "MN_CAPTURAS",
            descMenu: "Activacion de Survivor",
            icono: "lock-keyhole-open",
            numNivel: 2,
            urlMenu: "/captures/survivorActivation",
          },
        ],
      },
      {
        active: false,
        bHoja: false,
        cveAplicacion: "NFL",
        cveMenu: "MN_PROCESOS",
        cveMenuP: "root",
        descMenu: "Menu Procesos",
        icono: "bolt",
        numNivel: 1,
        urlMenu: "",
        children: [
          {
            active: false,
            aplicacion: "NFL",
            bHoja: true,
            cveAplicacion: "NFL",
            cveMenu: "F_PRO_APERT_PER",
            cveMenuP: "MN_PROCESOS",
            descMenu: "Proceso Apertura Quiniela",
            icono: "monitor-check",
            numNivel: 2,
            urlMenu: "/processes/periodOpening",
          },
          {
            active: false,
            aplicacion: "NFL",
            bHoja: true,
            cveAplicacion: "NFL",
            cveMenu: "F_PRO_CIERRE_PER",
            cveMenuP: "MN_PROCESOS",
            descMenu: "Proceso Cierre Periodo",
            icono: "monitor-x",
            numNivel: 2,
            urlMenu: "/processes/periodClosing",
          },
          {
            active: false,
            aplicacion: "NFL",
            bHoja: true,
            cveAplicacion: "NFL",
            cveMenu: "F_PRO_CIFRAS_QUIN",
            cveMenuP: "MN_PROCESOS",
            descMenu: "Verificacion Cifras Quiniela",
            icono: "shield-check",
            numNivel: 2,
            urlMenu: "/processes/quinielaVerification",
          },
        ],
      },
    ],
  },
];
