export const menuData = {
  active: false,
  aplicacion: "App1",
  bHoja: false,
  children: [
    {
      active: false,
      aplicacion: "App1",
      bHoja: true,
      cveAplicacion: "App1",
      cveMenu: "dashboard",
      cveMenuP: "root",
      descMenu: "Dashboard",
      icono: "check",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "/dashboard",
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: true,
      cveAplicacion: "App1",
      cveMenu: "matches",
      cveMenuP: "root",
      descMenu: "Matches",
      icono: "gamepad-2",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "/matches",
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "formas",
      cveMenuP: "root",
      descMenu: "Formas",
      icono: "file-question-mark",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "",
      children: [
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "forma_cliente",
          cveMenuP: "formas",
          descMenu: "Captura de cliente",
          icono: "edit",
          menuPadre: "formas",
          numNivel: 2,
          urlMenu: "/form/1",
        },
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "forma_quiniela",
          cveMenuP: "formas",
          descMenu: "Captura de quiniela",
          icono: "table-properties",
          menuPadre: "formas",
          numNivel: 2,
          urlMenu: "/form/2",
        },
      ],
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "quiniela",
      cveMenuP: "root",
      descMenu: "Quiniela",
      icono: "trophy",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "",
      children: [
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "captura_quiniela",
          cveMenuP: "quiniela",
          descMenu: "Captura de quiniela",
          icono: "edit",
          menuPadre: "quiniela",
          numNivel: 2,
          urlMenu: "/captura",
        },
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "posiciones_quiniela",
          cveMenuP: "quiniela",
          descMenu: "Posiciones quiniela",
          icono: "list-ordered",
          menuPadre: "quiniela",
          numNivel: 2,
          urlMenu: "/posiciones",
        },
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "historico_quinielas",
          cveMenuP: "quiniela",
          descMenu: "Histórico quinielas",
          icono: "history",
          menuPadre: "quiniela",
          numNivel: 2,
          urlMenu: "/historico",
        },
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "bolsa_acumulada",
          cveMenuP: "quiniela",
          descMenu: "Bolsa acumulada",
          icono: "hand-coins",
          menuPadre: "quiniela",
          numNivel: 2,
          urlMenu: "/bolsa",
        },
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "actualizacion_quiniela",
          cveMenuP: "quiniela",
          descMenu: "Actualización quiniela",
          icono: "list-ordered",
          menuPadre: "quiniela",
          numNivel: 2,
          urlMenu: "/actualizacion",
        },
      ],
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "survivor",
      cveMenuP: "root",
      descMenu: "Survivor",
      icono: "swords",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "/survivor",
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "marcadores",
      cveMenuP: "root",
      descMenu: "Marcadores",
      icono: "list-ordered",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "",
      children: [
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "captura_marcadores",
          cveMenuP: "marcadores",
          descMenu: "Captura de marcadores",
          icono: "pen",
          menuPadre: "marcadores",
          numNivel: 2,
          urlMenu: "/captura",
        },
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "consulta_marcadores",
          cveMenuP: "marcadores",
          descMenu: "Consulta marcadores",
          icono: "search",
          menuPadre: "marcadores",
          numNivel: 2,
          urlMenu: "/consulta",
        },
      ],
    },
    {
      active: false,
      aplicacion: "App1",
      bHoja: false,
      cveAplicacion: "App1",
      cveMenu: "settings",
      cveMenuP: "root",
      descMenu: "Settings",
      icono: "cog",
      menuPadre: "",
      numNivel: 1,
      urlMenu: "",
      children: [
        {
          active: false,
          aplicacion: "App1",
          bHoja: true,
          cveAplicacion: "App1",
          cveMenu: "profile",
          cveMenuP: "settings",
          descMenu: "Profile",
          icono: "user",
          menuPadre: "settings",
          numNivel: 2,
          urlMenu: "/profile",
        },
      ],
    },
  ],
  cveAplicacion: "App1",
  cveMenu: "root",
  cveMenuP: "",
  descMenu: "Main Menu",
  icono: "bars",
  menuPadre: "",
  numNivel: 0,
  urlMenu: "",
};
