export const menuAdmin = {
  active: false,
  aplicacion: "NFL",
  bHoja: false,
  cveAplicacion: "NFL",
  cveMenu: "root",
  cveMenuP: null,
  descMenu: null,
  icono: null,
  menuPadre: null,
  numNivel: 0,
  urlMenu: null,
  children: [
    {
      active: false,
      aplicacion: "NFL",
      bHoja: true,
      cveAplicacion: "NFL",
      cveMenu: "F_CON_PANEL_PRINCIPAL",
      cveMenuP: "root",
      descMenu: "Panel Principal",
      icono: "layout-dashboard",
      menuPadre: null,
      numNivel: 1,
      urlMenu: "/dashboard",
      children: null,
    },
    {
      active: false,
      aplicacion: "NFL",
      bHoja: true,
      cveAplicacion: "NFL",
      cveMenu: "F_CAP_QUINIELA",
      cveMenuP: "root",
      descMenu: "Captura Quinielas",
      icono: "square-pen",
      menuPadre: null,
      numNivel: 1,
      urlMenu: "/quinielaCapture",
      children: null,
    },
    {
      active: false,
      aplicacion: "NFL",
      bHoja: true,
      cveAplicacion: "NFL",
      cveMenu: "F_CON_POSICIONES",
      cveMenuP: "root",
      descMenu: "Consulta de Posiciones",
      icono: "list-ordered",
      menuPadre: null,
      numNivel: 1,
      urlMenu: "/positionQuery",
      children: null,
    },
    {
      active: false,
      aplicacion: "NFL",
      bHoja: true,
      cveAplicacion: "NFL",
      cveMenu: "F_CON_SURVIVOR",
      cveMenuP: "root",
      descMenu: "Consulta de Survivor",
      icono: "swords",
      menuPadre: null,
      numNivel: 1,
      urlMenu: "/survivorQuery",
      children: null,
    },
    {
      active: false,
      aplicacion: "NFL",
      bHoja: true,
      cveAplicacion: "NFL",
      cveMenu: "F_CON_MARCADORES",
      cveMenuP: "root",
      descMenu: "Consulta de Marcadores",
      icono: "file-digit",
      menuPadre: null,
      numNivel: 1,
      urlMenu: "/markerQuery",
      children: null,
    },
    {
      active: false,
      aplicacion: "NFL",
      bHoja: false,
      cveAplicacion: "NFL",
      cveMenu: "MN_CAPTURAS",
      cveMenuP: "root",
      descMenu: "Menú Capturas",
      icono: "notebook-tabs",
      menuPadre: null,
      numNivel: 1,
      urlMenu: null,
      children: [
        {
          active: false,
          aplicacion: "NFL",
          bHoja: true,
          cveAplicacion: "NFL",
          cveMenu: "F_CAP_SURVIVOR",
          cveMenuP: "MN_CAPTURAS",
          descMenu: "Activación de Survivor",
          icono: "lock-keyhole-open",
          menuPadre: "Menú Capturas",
          numNivel: 2,
          urlMenu: "/captures/survivorActivation",
          children: null,
        },
        {
          active: false,
          aplicacion: "NFL",
          bHoja: true,
          cveAplicacion: "NFL",
          cveMenu: "F_CAP_PAGO_SURV",
          cveMenuP: "MN_CAPTURAS",
          descMenu: "Pago de Survivor",
          icono: "hand-coins",
          menuPadre: "Menú Capturas",
          numNivel: 2,
          urlMenu: "/captures/survivorPayment",
          children: null,
        },
        {
          active: false,
          aplicacion: "NFL",
          bHoja: true,
          cveAplicacion: "NFL",
          cveMenu: "F_CAP_MARCADORES",
          cveMenuP: "MN_CAPTURAS",
          descMenu: "Captura de Marcadores",
          icono: "notebook-pen",
          menuPadre: "Menú Capturas",
          numNivel: 2,
          urlMenu: "/captures/markerCapture",
          children: null,
        },
      ],
    },
    {
      active: false,
      aplicacion: "NFL",
      bHoja: false,
      cveAplicacion: "NFL",
      cveMenu: "MN_PROCESOS",
      cveMenuP: "root",
      descMenu: "Menú Procesos",
      icono: "bolt",
      menuPadre: null,
      numNivel: 1,
      urlMenu: null,
      children: [
        {
          active: false,
          aplicacion: "NFL",
          bHoja: true,
          cveAplicacion: "NFL",
          cveMenu: "F_PRO_CIERRE_PER",
          cveMenuP: "MN_PROCESOS",
          descMenu: "Proceso de Cierre de Periodo",
          icono: "monitor-x",
          menuPadre: "Menú Procesos",
          numNivel: 2,
          urlMenu: "/processes/periodClosing",
          children: null,
        },
        {
          active: false,
          aplicacion: "NFL",
          bHoja: true,
          cveAplicacion: "NFL",
          cveMenu: "F_PRO_APERT_PER",
          cveMenuP: "MN_PROCESOS",
          descMenu: "Proceso de Apertura de Periodo",
          icono: "monitor-check",
          menuPadre: "Menú Procesos",
          numNivel: 2,
          urlMenu: "/processes/periodOpening",
          children: null,
        },
        {
          active: false,
          aplicacion: "NFL",
          bHoja: true,
          cveAplicacion: "NFL",
          cveMenu: "F_PRO_CIFRAS_QUIN",
          cveMenuP: "MN_PROCESOS",
          descMenu: "Verificación de Cifras Quiniela",
          icono: "shield-check",
          menuPadre: "Menú Procesos",
          numNivel: 2,
          urlMenu: "/processes/quinielaVerification",
          children: null,
        },
      ],
    },
  ],
};
