export const pagos = [
  {
    ID_PARTICIPANTE: 1,
    NOM_PARTICIPANTE: "EFREN AVILA",
    ID_EQUIPO_SUV: 13,
    NOM_EQUIPO: "Cleveland Browns",
    B_PAGO: true,
  },
  {
    ID_PARTICIPANTE: 2,
    NOM_PARTICIPANTE: "LUIS O. ALVAREZ",
    ID_EQUIPO_SUV: 14,
    NOM_EQUIPO: "Buffalo Bills",
    B_PAGO: false,
  },
  {
    ID_PARTICIPANTE: 3,
    NOM_PARTICIPANTE: "DUSTIN CRUZ",
    ID_EQUIPO_SUV: 32,
    NOM_EQUIPO: "Detroit Lions",
    B_PAGO: false,
  },
  {
    ID_PARTICIPANTE: 5,
    NOM_PARTICIPANTE: "GUSTAVO SOLIS",
    ID_EQUIPO_SUV: 14,
    NOM_EQUIPO: "Buffalo Bills",
    B_PAGO: false,
  },
  {
    ID_PARTICIPANTE: 6,
    NOM_PARTICIPANTE: "HECTOR ALVAREZ",
    ID_EQUIPO_SUV: 25,
    NOM_EQUIPO: "Tampa Bay Bucaneers",
    B_PAGO: false,
  },
  {
    ID_PARTICIPANTE: 7,
    NOM_PARTICIPANTE: "JONATAN PARRA",
    ID_EQUIPO_SUV: 13,
    NOM_EQUIPO: "Cleveland Browns",
    B_PAGO: false,
  },
  {
    ID_PARTICIPANTE: 8,
    NOM_PARTICIPANTE: "MARIO LOPEZ",
    ID_EQUIPO_SUV: 13,
    NOM_EQUIPO: "Cleveland Browns",
    B_PAGO: true,
  },
  {
    ID_PARTICIPANTE: 10,
    NOM_PARTICIPANTE: "ALEJANDRO ORTEGA",
    ID_EQUIPO_SUV: 10,
    NOM_EQUIPO: "New England Patriots",
    B_PAGO: true,
  },
  {
    ID_PARTICIPANTE: 11,
    NOM_PARTICIPANTE: "PEDRO CANEDO",
    ID_EQUIPO_SUV: 16,
    NOM_EQUIPO: "Seattle Seahawks",
    B_PAGO: false,
  },
  {
    ID_PARTICIPANTE: 12,
    NOM_PARTICIPANTE: "DIEGO OJEDA",
    ID_EQUIPO_SUV: 12,
    NOM_EQUIPO: "Kansas City Chiefs",
    B_PAGO: false,
  },
  {
    ID_PARTICIPANTE: 13,
    NOM_PARTICIPANTE: "DAVID ALVARADO",
    ID_EQUIPO_SUV: 20,
    NOM_EQUIPO: "Houston Texans",
    B_PAGO: false,
  },
  {
    ID_PARTICIPANTE: 14,
    NOM_PARTICIPANTE: "HUMBERTO LOPEZ",
    ID_EQUIPO_SUV: 25,
    NOM_EQUIPO: "Tampa Bay Bucaneers",
    B_PAGO: true,
  },
];
