export const partidos2 = [
  {
    quiniela: [
      {
        Partido: 1,
        IdV: 16,
        EquipoV: "Seattle Seahawks",
        IdL: 27,
        EquipoL: "Arizona Cardinals",
        Fecha: "2025-09-25",
        HoraPartido: "06:15:00 p. m.",
        Estadio: '"State Farm Stadium, Glendale, AZ"',
        partGanador: "V",
        scoreVist: 21,
        scoreLocal: 20,
        numGanadosV: 3,
        numPerdidosV: 1,
        numEmpatadosV: 0,
        numGanadosL: 2,
        numPerdidosL: 2,
        numEmpatadosL: 0,
      },
      {
        Partido: 2,
        IdV: 6,
        EquipoV: "Minnesota Vikings",
        IdL: 7,
        EquipoL: "Pittsburgh Steelers",
        Fecha: "2025-09-28",
        HoraPartido: "07:30:00 a. m.",
        Estadio: '"Croke Park, Dublin, Irlanda"',
        partGanador: "L",
        scoreVist: 21,
        scoreLocal: 24,
        numGanadosV: 2,
        numPerdidosV: 2,
        numEmpatadosV: 0,
        numGanadosL: 3,
        numPerdidosL: 1,
        numEmpatadosL: 0,
      },
      {
        Partido: 3,
        IdV: 11,
        EquipoV: "Washington Comanders",
        IdL: 19,
        EquipoL: "Atlanta Falcons",
        Fecha: "2025-09-28",
        HoraPartido: "11:00:00 a. m.",
        Estadio: '"Mercedes-Benz Stadium, Atlanta, GA"',
        partGanador: "V",
        scoreVist: 27,
        scoreLocal: 34,
        numGanadosV: 2,
        numPerdidosV: 2,
        numEmpatadosV: 0,
        numGanadosL: 2,
        numPerdidosL: 2,
        numEmpatadosL: 0,
      },
      {
        Partido: 4,
        IdV: 3,
        EquipoV: "New Orleans Saints",
        IdL: 14,
        EquipoL: "Buffalo Bills",
        Fecha: "2025-09-28",
        HoraPartido: "11:00:00 a. m.",
        Estadio: '"Highmark Stadium, Orchard Park, NY"',
        partGanador: "L",
        scoreVist: 19,
        scoreLocal: 31,
        numGanadosV: 0,
        numPerdidosV: 4,
        numEmpatadosV: 0,
        numGanadosL: 4,
        numPerdidosL: 0,
        numEmpatadosL: 0,
      },
      {
        Partido: 5,
        IdV: 13,
        EquipoV: "Cleveland Browns",
        IdL: 32,
        EquipoL: "Detroit Lions",
        Fecha: "2025-09-28",
        HoraPartido: "11:00:00 a. m.",
        Estadio: '"Ford Field, Detroit, MI"',
        partGanador: "L",
        scoreVist: 10,
        scoreLocal: 34,
        numGanadosV: 1,
        numPerdidosV: 3,
        numEmpatadosV: 0,
        numGanadosL: 3,
        numPerdidosL: 1,
        numEmpatadosL: 0,
      },
      {
        Partido: 6,
        IdV: 18,
        EquipoV: "Carolina Panthers",
        IdL: 10,
        EquipoL: "New England Patriots",
        Fecha: "2025-09-28",
        HoraPartido: "11:00:00 a. m.",
        Estadio: '"Gillette Stadium, Foxborough, MA"',
        partGanador: "L",
        scoreVist: 13,
        scoreLocal: 42,
        numGanadosV: 1,
        numPerdidosV: 3,
        numEmpatadosV: 0,
        numGanadosL: 2,
        numPerdidosL: 2,
        numEmpatadosL: 0,
      },
      {
        Partido: 7,
        IdV: 28,
        EquipoV: "Los Angeles Chargers",
        IdL: 17,
        EquipoL: "New York Giants",
        Fecha: "2025-09-28",
        HoraPartido: "11:00:00 a. m.",
        Estadio: '"MetLife Stadium, East Rutherford, NJ"',
        partGanador: "V",
        scoreVist: 18,
        scoreLocal: 21,
        numGanadosV: 3,
        numPerdidosV: 1,
        numEmpatadosV: 0,
        numGanadosL: 1,
        numPerdidosL: 3,
        numEmpatadosL: 0,
      },
      {
        Partido: 8,
        IdV: 9,
        EquipoV: "Philadelphia Eagles",
        IdL: 25,
        EquipoL: "Tampa Bay Bucaneers",
        Fecha: "2025-09-28",
        HoraPartido: "11:00:00 a. m.",
        Estadio: '"Raymond James Stadium, Tampa, FL"',
        partGanador: "V",
        scoreVist: 31,
        scoreLocal: 25,
        numGanadosV: 4,
        numPerdidosV: 0,
        numEmpatadosV: 0,
        numGanadosL: 3,
        numPerdidosL: 1,
        numEmpatadosL: 0,
      },
      {
        Partido: 9,
        IdV: 15,
        EquipoV: "Tennessee  Titans",
        IdL: 20,
        EquipoL: "Houston Texans",
        Fecha: "2025-09-28",
        HoraPartido: "11:00:00 a. m.",
        Estadio: '"NRG Stadium, Houston, TX"',
        partGanador: "L",
        scoreVist: 0,
        scoreLocal: 26,
        numGanadosV: 0,
        numPerdidosV: 4,
        numEmpatadosV: 0,
        numGanadosL: 1,
        numPerdidosL: 3,
        numEmpatadosL: 0,
      },
      {
        Partido: 10,
        IdV: 23,
        EquipoV: "Indianapolis Colts",
        IdL: 8,
        EquipoL: "Los Angeles Rams",
        Fecha: "2025-09-28",
        HoraPartido: "02:05:00 p. m.",
        Estadio: '"SoFi Stadium, Inglewood, CA"',
        partGanador: "L",
        scoreVist: 20,
        scoreLocal: 27,
        numGanadosV: 3,
        numPerdidosV: 1,
        numEmpatadosV: 0,
        numGanadosL: 3,
        numPerdidosL: 1,
        numEmpatadosL: 0,
      },
      {
        Partido: 11,
        IdV: 4,
        EquipoV: "Jacksonville Jaguars",
        IdL: 26,
        EquipoL: "San Francisco 49ers",
        Fecha: "2025-09-28",
        HoraPartido: "02:05:00 p. m.",
        Estadio: '"Levi\'s Stadium, Santa Clara, CA"',
        partGanador: "L",
        scoreVist: 26,
        scoreLocal: 21,
        numGanadosV: 3,
        numPerdidosV: 1,
        numEmpatadosV: 0,
        numGanadosL: 3,
        numPerdidosL: 1,
        numEmpatadosL: 0,
      },
      {
        Partido: 12,
        IdV: 30,
        EquipoV: "Baltimore Ravens",
        IdL: 12,
        EquipoL: "Kansas City Chiefs",
        Fecha: "2025-09-28",
        HoraPartido: "02:25:00 p. m.",
        Estadio: '"GEHA Field at Arrowhead Stadium, Kansas City, MO"',
        partGanador: "L",
        scoreVist: 20,
        scoreLocal: 37,
        numGanadosV: 1,
        numPerdidosV: 3,
        numEmpatadosV: 0,
        numGanadosL: 2,
        numPerdidosL: 2,
        numEmpatadosL: 0,
      },
      {
        Partido: 13,
        IdV: 24,
        EquipoV: "Chicago Bears",
        IdL: 29,
        EquipoL: "Las Vegas Raiders",
        Fecha: "2025-09-28",
        HoraPartido: "02:25:00 p. m.",
        Estadio: '"Allegiant Stadium, Las Vegas, NV"',
        partGanador: "V",
        scoreVist: 25,
        scoreLocal: 24,
        numGanadosV: 2,
        numPerdidosV: 2,
        numEmpatadosV: 0,
        numGanadosL: 1,
        numPerdidosL: 3,
        numEmpatadosL: 0,
      },
      {
        Partido: 14,
        IdV: 22,
        EquipoV: "Green Bay Packers",
        IdL: 1,
        EquipoL: "Dallas Cowboys",
        Fecha: "2025-09-28",
        HoraPartido: "06:20:00 p. m.",
        Estadio: '"AT&T Stadium, Arlington, TX"',
        partGanador: "V",
        scoreVist: 40,
        scoreLocal: 40,
        numGanadosV: 2,
        numPerdidosV: 1,
        numEmpatadosV: 1,
        numGanadosL: 1,
        numPerdidosL: 2,
        numEmpatadosL: 1,
      },
      {
        Partido: 15,
        IdV: 21,
        EquipoV: "New York Jets",
        IdL: 31,
        EquipoL: "Miami Dolphins",
        Fecha: "2025-09-29",
        HoraPartido: "05:15:00 p. m.",
        Estadio: '"Hard Rock Stadium, Miami Gardens, FL"',
        partGanador: "V",
        scoreVist: 21,
        scoreLocal: 27,
        numGanadosV: 0,
        numPerdidosV: 4,
        numEmpatadosV: 0,
        numGanadosL: 1,
        numPerdidosL: 3,
        numEmpatadosL: 0,
      },
      {
        Partido: 16,
        IdV: 2,
        EquipoV: "Cincinnati Bengals",
        IdL: 5,
        EquipoL: "Denver Broncos",
        Fecha: "2025-09-29",
        HoraPartido: "06:15:00 p. m.",
        Estadio: '"Empower Field at Mile High, Denver, CO"',
        partGanador: "L",
        scoreVist: 3,
        scoreLocal: 28,
        numGanadosV: 2,
        numPerdidosV: 2,
        numEmpatadosV: 0,
        numGanadosL: 2,
        numPerdidosL: 2,
        numEmpatadosL: 0,
      },
    ],
    bye: null,
    extraData: {
      bQuiniela: 1,
      nomSurvivor: "Buffalo Bills",
    },
  },
];
