export const partidos = [
  {
    quin1ela: [
      {
        Partido: 1,
        IdL: 30,
        EquipoL: "Baltimore Ravens",
        IdV: 2,
        EquipoV: "Cincinnati Bengals",
        Fecha: "2024-11-07",
        HoraPartido: "19:15",
        Estadio: " ",
      },
      {
        Partido: 2,
        IdL: 18,
        EquipoL: "Carolina Panthers",
        IdV: 17,
        EquipoV: "New York Giants",
        Fecha: "2024-11-10",
        HoraPartido: "8:30",
        Estadio: " ",
      },
      {
        Partido: 3,
        IdL: 24,
        EquipoL: "Chicago Bears",
        IdV: 10,
        EquipoV: "New England Patriots",
        Fecha: "2024-11-10",
        HoraPartido: "12:00",
        Estadio: " ",
      },
      {
        Partido: 4,
        IdL: 23,
        EquipoL: "Indianapolis Colts",
        IdV: 14,
        EquipoV: "Buffalo Bills",
        Fecha: "2024-11-10",
        HoraPartido: "12:00",
        Estadio: " ",
      },
      {
        Partido: 5,
        IdL: 12,
        EquipoL: "Kansas City Chiefs",
        IdV: 5,
        EquipoV: "Denver Broncos",
        Fecha: "2024-11-10",
        HoraPartido: "12:00",
        Estadio: " ",
      },
      {
        Partido: 6,
        IdL: 3,
        EquipoL: "New Orleans Saints",
        IdV: 19,
        EquipoV: "Atlanta Falcons",
        Fecha: "2024-11-10",
        HoraPartido: "12:00",
        Estadio: " ",
      },
      {
        Partido: 7,
        IdL: 25,
        EquipoL: "Tampa Bay Bucaneers",
        IdV: 26,
        EquipoV: "San Francisco 49ers",
        Fecha: "2024-11-10",
        HoraPartido: "12:00",
        Estadio: " ",
      },
      {
        Partido: 8,
        IdL: 11,
        EquipoL: "Washington Comanders",
        IdV: 7,
        EquipoV: "Pittsburgh Steelers",
        Fecha: "2024-11-10",
        HoraPartido: "12:00",
        Estadio: " ",
      },
      {
        Partido: 9,
        IdL: 4,
        EquipoL: "Jacksonville Jaguars",
        IdV: 6,
        EquipoV: "Minnesota Vikings",
        Fecha: "2024-11-10",
        HoraPartido: "12:00",
        Estadio: " ",
      },
      {
        Partido: 10,
        IdL: 28,
        EquipoL: "Los Angeles Chargers ",
        IdV: 15,
        EquipoV: "Tennessee  Titans",
        Fecha: "2024-11-10",
        HoraPartido: "15:05",
        Estadio: " ",
      },
      {
        Partido: 11,
        IdL: 1,
        EquipoL: "Dallas Cowboys",
        IdV: 9,
        EquipoV: "Philadelphia Eagles",
        Fecha: "2024-11-10",
        HoraPartido: "15:25",
        Estadio: " ",
      },
      {
        Partido: 12,
        IdL: 27,
        EquipoL: "Arizona Cardinals",
        IdV: 21,
        EquipoV: "New York Jets",
        Fecha: "2024-11-10",
        HoraPartido: "15:25",
        Estadio: " ",
      },
      {
        Partido: 13,
        IdL: 20,
        EquipoL: "Houston Texans",
        IdV: 32,
        EquipoV: "Detroit Lions",
        Fecha: "2024-11-10",
        HoraPartido: "19:20",
        Estadio: " ",
      },
      {
        Partido: 14,
        IdL: 8,
        EquipoL: "Los Angeles Rams",
        IdV: 31,
        EquipoV: "Miami Dolphins",
        Fecha: "2024-11-11",
        HoraPartido: "19:15",
        Estadio: " ",
      },
    ],
    bye: [
      {
        IdEquipo: 13,
        NomEquipo: "Cleveland Browns",
      },
      {
        IdEquipo: 16,
        NomEquipo: "Seattle Seahawks",
      },
      {
        IdEquipo: 22,
        NomEquipo: "Green Bay Packers",
      },
      {
        IdEquipo: 29,
        NomEquipo: "Las Vegas Raiders",
      },
    ],
  },
];
