export const partidos = [
  {
    quinela: [
      {
        idPartido: 1,
        idEquipo1: 9,
        equipo1: "Philadelphia Eagles",
        idEquipo2: 11,
        equipo2: "Washington Comanders",
        F_PARTIDO: "2024-11-14",
        HORA_PARTIDO: "19:15",
        ESTADIO: " ",
      },
      {
        idPartido: 2,
        idEquipo1: 24,
        equipo1: "Chicago Bears",
        idEquipo2: 22,
        equipo2: "Green Bay Packers",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "12:00",
        ESTADIO: " ",
      },
      {
        idPartido: 3,
        idEquipo1: 32,
        equipo1: "Detroit Lions",
        idEquipo2: 4,
        equipo2: "Jacksonville Jaguars",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "12:00",
        ESTADIO: " ",
      },
      {
        idPartido: 4,
        idEquipo1: 15,
        equipo1: "Tennessee  Titans",
        idEquipo2: 6,
        equipo2: "Minnesota Vikings",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "12:00",
        ESTADIO: " ",
      },
      {
        idPartido: 5,
        idEquipo1: 31,
        equipo1: "Miami Dolphins",
        idEquipo2: 29,
        equipo2: "Las Vegas Raiders",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "12:00",
        ESTADIO: " ",
      },
      {
        idPartido: 6,
        idEquipo1: 10,
        equipo1: "New England Patriots",
        idEquipo2: 8,
        equipo2: "Los Angeles Rams",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "12:00",
        ESTADIO: " ",
      },
      {
        idPartido: 7,
        idEquipo1: 3,
        equipo1: "New Orleans Saints",
        idEquipo2: 13,
        equipo2: "Cleveland Browns",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "12:00",
        ESTADIO: " ",
      },
      {
        idPartido: 8,
        idEquipo1: 7,
        equipo1: "Pittsburgh Steelers",
        idEquipo2: 30,
        equipo2: "Baltimore Ravens",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "12:00",
        ESTADIO: " ",
      },
      {
        idPartido: 9,
        idEquipo1: 5,
        equipo1: "Denver Broncos",
        idEquipo2: 19,
        equipo2: "Atlanta Falcons",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "15:05",
        ESTADIO: " ",
      },
      {
        idPartido: 10,
        idEquipo1: 26,
        equipo1: "San Francisco 49ers",
        idEquipo2: 16,
        equipo2: "Seattle Seahawks",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "15:05",
        ESTADIO: " ",
      },
      {
        idPartido: 11,
        idEquipo1: 14,
        equipo1: "Buffalo Bills",
        idEquipo2: 12,
        equipo2: "Kansas City Chiefs",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "15:25",
        ESTADIO: " ",
      },
      {
        idPartido: 12,
        idEquipo1: 28,
        equipo1: "Los Angeles Chargers ",
        idEquipo2: 2,
        equipo2: "Cincinnati Bengals",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "15:25",
        ESTADIO: " ",
      },
      {
        idPartido: 13,
        idEquipo1: 21,
        equipo1: "New York Jets",
        idEquipo2: 23,
        equipo2: "Indianapolis Colts",
        F_PARTIDO: "2024-11-17",
        HORA_PARTIDO: "19:20",
        ESTADIO: " ",
      },
      {
        idPartido: 14,
        idEquipo1: 1,
        equipo1: "Dallas Cowboys",
        idEquipo2: 20,
        equipo2: "Houston Texans",
        F_PARTIDO: "2024-11-18",
        HORA_PARTIDO: "19:15",
        ESTADIO: " ",
      },
    ],
    bye: [
      {
        idEquipo: 17,
        nomEquipo: "New York Giants",
      },
      {
        idEquipo: 18,
        nomEquipo: "Carolina Panthers",
      },
      {
        idEquipo: 25,
        nomEquipo: "Tampa Bay Bucaneers",
      },
      {
        idEquipo: 27,
        nomEquipo: "Arizona Cardinals",
      },
    ],
  },
];
