export const posicionesParticipantes = [
  {
    puntosPeriodo: [
      {
        Posicion: 1,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 1,
        periodo: "7",
        Nombre: "EFREN AVILA",
        Puntos: 12,
      },
      {
        Posicion: 1,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 12,
        periodo: "7",
        Nombre: "DIEGO OJEDA",
        Puntos: 12,
      },
      {
        Posicion: 2,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 7,
        periodo: "7",
        Nombre: "JONATAN PARRA",
        Puntos: 11,
      },
      {
        Posicion: 2,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 3,
        periodo: "7",
        Nombre: "DUSTIN CRUZ",
        Puntos: 11,
      },
      {
        Posicion: 3,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 4,
        periodo: "7",
        Nombre: "KAREN PEREZ",
        Puntos: 10,
      },
      {
        Posicion: 3,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 5,
        periodo: "7",
        Nombre: "GUSTAVO SOLIS",
        Puntos: 10,
      },
      {
        Posicion: 3,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 6,
        periodo: "7",
        Nombre: "HECTOR ALVAREZ",
        Puntos: 10,
      },
      {
        Posicion: 3,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 9,
        periodo: "7",
        Nombre: "NATALIA CASTILLO",
        Puntos: 10,
      },
      {
        Posicion: 4,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 14,
        periodo: "7",
        Nombre: "HUMBERTO LOPEZ",
        Puntos: 9,
      },
      {
        Posicion: 5,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 10,
        periodo: "7",
        Nombre: "ALEJANDRO ORTEGA",
        Puntos: 8,
      },
      {
        Posicion: 5,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 11,
        periodo: "7",
        Nombre: "PEDRO CANEDO",
        Puntos: 8,
      },
      {
        Posicion: 5,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 8,
        periodo: "7",
        Nombre: "MARIO LOPEZ",
        Puntos: 8,
      },
      {
        Posicion: 5,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 2,
        periodo: "7",
        Nombre: "LUIS O. ALVAREZ",
        Puntos: 8,
      },
      {
        Posicion: 6,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 13,
        periodo: "7",
        Nombre: "DAVID ALVARADO",
        Puntos: 7,
      },
    ],
    puntosTotal: [
      {
        Posicion: 1,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 1,
        Nombre: "EFREN AVILA",
        Puntos: 82,
      },
      {
        Posicion: 1,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 12,
        Nombre: "DIEGO OJEDA",
        Puntos: 82,
      },
      {
        Posicion: 2,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 14,
        Nombre: "HUMBERTO LOPEZ",
        Puntos: 80,
      },
      {
        Posicion: 2,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 7,
        Nombre: "JONATAN PARRA",
        Puntos: 80,
      },
      {
        Posicion: 3,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 3,
        Nombre: "DUSTIN CRUZ",
        Puntos: 79,
      },
      {
        Posicion: 3,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 5,
        Nombre: "GUSTAVO SOLIS",
        Puntos: 79,
      },
      {
        Posicion: 4,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 6,
        Nombre: "HECTOR ALVAREZ",
        Puntos: 78,
      },
      {
        Posicion: 5,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 8,
        Nombre: "MARIO LOPEZ",
        Puntos: 77,
      },
      {
        Posicion: 6,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 11,
        Nombre: "PEDRO CANEDO",
        Puntos: 76,
      },
      {
        Posicion: 7,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 9,
        Nombre: "NATALIA CASTILLO",
        Puntos: 75,
      },
      {
        Posicion: 7,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 4,
        Nombre: "KAREN PEREZ",
        Puntos: 75,
      },
      {
        Posicion: 8,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 10,
        Nombre: "ALEJANDRO ORTEGA",
        Puntos: 73,
      },
      {
        Posicion: 9,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 2,
        Nombre: "LUIS O. ALVAREZ",
        Puntos: 72,
      },
      {
        Posicion: 10,
        ID_QUINIELA: 1,
        ID_PARTICIPANTE: 13,
        Nombre: "DAVID ALVARADO",
        Puntos: 68,
      },
    ],
  },
];
