export const survivorRanking = [
  {
    ID_PARTICIPANTE: 11,
    NOM_PARTICIPANTE: "PEDRO CANEDO",
    NUM_SUVIVORS: 12,
    NUM_ACIERTOS: 11,
    IMP_INVERSION: 0,
    NOM_EQ_1: "Texans ",
    NOM_EQ_2: "Jets ",
    NOM_EQ_3: "Seahawks ",
    NOM_EQ_4: "Raiders ",
    NOM_EQ_5: "Bears ",
    NOM_EQ_6: "Buccaneers ",
    NOM_EQ_7: "Commanders ",
    NOM_EQ_8: "Steelers ",
    NOM_EQ_9: "Eagles ",
    NOM_EQ_10: "Vikings ",
    NOM_EQ_11: "Lions ",
    NOM_EQ_12: "Chiefs(P)",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 2,
    NOM_PARTICIPANTE: "LUIS O. ALVAREZ",
    NUM_SUVIVORS: 12,
    NUM_ACIERTOS: 10,
    IMP_INVERSION: 250,
    NOM_EQ_1: "Chiefs ",
    NOM_EQ_2: "Texans ",
    NOM_EQ_3: "Bills ",
    NOM_EQ_4: "49ers ",
    NOM_EQ_5: "Seahawks(X)",
    NOM_EQ_6: "Eagles ",
    NOM_EQ_7: "Commanders ",
    NOM_EQ_8: "Broncos ",
    NOM_EQ_9: "Falcons ",
    NOM_EQ_10: "Ravens ",
    NOM_EQ_11: "Vikings ",
    NOM_EQ_12: "Dolphins(P)",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 8,
    NOM_PARTICIPANTE: "MARIO LOPEZ",
    NUM_SUVIVORS: 12,
    NUM_ACIERTOS: 8,
    IMP_INVERSION: 550,
    NOM_EQ_1: "49ers ",
    NOM_EQ_2: "Commanders ",
    NOM_EQ_3: "Browns(X)",
    NOM_EQ_4: "Dolphins(X)",
    NOM_EQ_5: "Patriots(X)",
    NOM_EQ_6: "Eagles ",
    NOM_EQ_7: "Bills ",
    NOM_EQ_8: "Broncos ",
    NOM_EQ_9: "Vikings ",
    NOM_EQ_10: "Chiefs ",
    NOM_EQ_11: "Texans ",
    NOM_EQ_12: "Lions(P)",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 1,
    NOM_PARTICIPANTE: "EFREN AVILA",
    NUM_SUVIVORS: 12,
    NUM_ACIERTOS: 8,
    IMP_INVERSION: 550,
    NOM_EQ_1: "Texans ",
    NOM_EQ_2: "Commanders ",
    NOM_EQ_3: "Browns(X)",
    NOM_EQ_4: "Rams(X)",
    NOM_EQ_5: "Seahawks(X)",
    NOM_EQ_6: "Eagles ",
    NOM_EQ_7: "Bills ",
    NOM_EQ_8: "Lions ",
    NOM_EQ_9: "Ravens ",
    NOM_EQ_10: "Chargers ",
    NOM_EQ_11: "Dolphins ",
    NOM_EQ_12: "Buccaneers(P)",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 10,
    NOM_PARTICIPANTE: "ALEJANDRO ORTEGA",
    NUM_SUVIVORS: 12,
    NUM_ACIERTOS: 7,
    IMP_INVERSION: 950,
    NOM_EQ_1: "Dolphins ",
    NOM_EQ_2: "Bills ",
    NOM_EQ_3: "Patriots(X)",
    NOM_EQ_4: "Saints(X)",
    NOM_EQ_5: "Vikings ",
    NOM_EQ_6: "Commanders(X)",
    NOM_EQ_7: "Ravens ",
    NOM_EQ_8: "Cowboys(X)",
    NOM_EQ_9: "Chiefs ",
    NOM_EQ_10: "Steelers ",
    NOM_EQ_11: "Chargers ",
    NOM_EQ_12: "Packers(P)",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 5,
    NOM_PARTICIPANTE: "GUSTAVO SOLIS",
    NUM_SUVIVORS: 12,
    NUM_ACIERTOS: 7,
    IMP_INVERSION: 950,
    NOM_EQ_1: "Bengals(X)",
    NOM_EQ_2: "Eagles(X)",
    NOM_EQ_3: "Bills ",
    NOM_EQ_4: "49ers ",
    NOM_EQ_5: "Seahawks(X)",
    NOM_EQ_6: "Falcons ",
    NOM_EQ_7: "Commanders ",
    NOM_EQ_8: "Ravens(X)",
    NOM_EQ_9: "Chiefs ",
    NOM_EQ_10: "Vikings ",
    NOM_EQ_11: "Lions ",
    NOM_EQ_12: "Dolphins(P)",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 14,
    NOM_PARTICIPANTE: "HUMBERTO LOPEZ",
    NUM_SUVIVORS: 10,
    NUM_ACIERTOS: 5,
    IMP_INVERSION: 850,
    NOM_EQ_1: "Bears ",
    NOM_EQ_2: "Colts(X)",
    NOM_EQ_3: "Buccaneers(X)",
    NOM_EQ_4: "Jets(X)",
    NOM_EQ_5: "Broncos ",
    NOM_EQ_6: "Eagles ",
    NOM_EQ_7: "Steelers ",
    NOM_EQ_8: "Dolphins(X)",
    NOM_EQ_9: "Ravens ",
    NOM_EQ_10: "Giants(X)",
    NOM_EQ_11: " ",
    NOM_EQ_12: " ",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 3,
    NOM_PARTICIPANTE: "DUSTIN CRUZ",
    NUM_SUVIVORS: 9,
    NUM_ACIERTOS: 6,
    IMP_INVERSION: 400,
    NOM_EQ_1: "Steelers ",
    NOM_EQ_2: "Colts(X)",
    NOM_EQ_3: "Lions ",
    NOM_EQ_4: "Vikings ",
    NOM_EQ_5: "Patriots(X)",
    NOM_EQ_6: "Bears ",
    NOM_EQ_7: "Broncos ",
    NOM_EQ_8: "Cardinals ",
    NOM_EQ_9: "Texans(X)",
    NOM_EQ_10: " ",
    NOM_EQ_11: " ",
    NOM_EQ_12: " ",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 12,
    NOM_PARTICIPANTE: "DIEGO OJEDA",
    NUM_SUVIVORS: 5,
    NUM_ACIERTOS: 4,
    IMP_INVERSION: 0,
    NOM_EQ_1: "Lions ",
    NOM_EQ_2: "Chargers ",
    NOM_EQ_3: "Chiefs ",
    NOM_EQ_4: "Vikings ",
    NOM_EQ_5: "49ers(X)",
    NOM_EQ_6: " ",
    NOM_EQ_7: " ",
    NOM_EQ_8: " ",
    NOM_EQ_9: " ",
    NOM_EQ_10: " ",
    NOM_EQ_11: " ",
    NOM_EQ_12: " ",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 13,
    NOM_PARTICIPANTE: "DAVID ALVARADO",
    NUM_SUVIVORS: 3,
    NUM_ACIERTOS: 2,
    IMP_INVERSION: 0,
    NOM_EQ_1: "Lions ",
    NOM_EQ_2: "Chargers ",
    NOM_EQ_3: "Texans(X)",
    NOM_EQ_4: " ",
    NOM_EQ_5: " ",
    NOM_EQ_6: " ",
    NOM_EQ_7: " ",
    NOM_EQ_8: " ",
    NOM_EQ_9: " ",
    NOM_EQ_10: " ",
    NOM_EQ_11: " ",
    NOM_EQ_12: " ",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 6,
    NOM_PARTICIPANTE: "HECTOR ALVAREZ",
    NUM_SUVIVORS: 3,
    NUM_ACIERTOS: 1,
    IMP_INVERSION: 150,
    NOM_EQ_1: "Ravens(X)",
    NOM_EQ_2: "Cardinals ",
    NOM_EQ_3: "Buccaneers(X)",
    NOM_EQ_4: " ",
    NOM_EQ_5: " ",
    NOM_EQ_6: " ",
    NOM_EQ_7: " ",
    NOM_EQ_8: " ",
    NOM_EQ_9: " ",
    NOM_EQ_10: " ",
    NOM_EQ_11: " ",
    NOM_EQ_12: " ",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 7,
    NOM_PARTICIPANTE: "JONATAN PARRA",
    NUM_SUVIVORS: 3,
    NUM_ACIERTOS: 1,
    IMP_INVERSION: 150,
    NOM_EQ_1: "49ers ",
    NOM_EQ_2: "Eagles(X)",
    NOM_EQ_3: "Browns(X)",
    NOM_EQ_4: " ",
    NOM_EQ_5: " ",
    NOM_EQ_6: " ",
    NOM_EQ_7: " ",
    NOM_EQ_8: " ",
    NOM_EQ_9: " ",
    NOM_EQ_10: " ",
    NOM_EQ_11: " ",
    NOM_EQ_12: " ",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 4,
    NOM_PARTICIPANTE: "KAREN PEREZ",
    NUM_SUVIVORS: 2,
    NUM_ACIERTOS: 1,
    IMP_INVERSION: 0,
    NOM_EQ_1: "Buccaneers ",
    NOM_EQ_2: "Jaguars(X)",
    NOM_EQ_3: " ",
    NOM_EQ_4: " ",
    NOM_EQ_5: " ",
    NOM_EQ_6: " ",
    NOM_EQ_7: " ",
    NOM_EQ_8: " ",
    NOM_EQ_9: " ",
    NOM_EQ_10: " ",
    NOM_EQ_11: " ",
    NOM_EQ_12: " ",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
  {
    ID_PARTICIPANTE: 9,
    NOM_PARTICIPANTE: "NATALIA CASTILLO",
    NUM_SUVIVORS: 1,
    NUM_ACIERTOS: 0,
    IMP_INVERSION: 0,
    NOM_EQ_1: "Bengals(X)",
    NOM_EQ_2: " ",
    NOM_EQ_3: " ",
    NOM_EQ_4: " ",
    NOM_EQ_5: " ",
    NOM_EQ_6: " ",
    NOM_EQ_7: " ",
    NOM_EQ_8: " ",
    NOM_EQ_9: " ",
    NOM_EQ_10: " ",
    NOM_EQ_11: " ",
    NOM_EQ_12: " ",
    NOM_EQ_13: " ",
    NOM_EQ_14: " ",
    NOM_EQ_15: " ",
    NOM_EQ_16: " ",
    NOM_EQ_17: " ",
  },
];
