export const tablaMarcadores = [
  {
    partido: 1,
    idEquipo1: 9,
    nomEquipo1: "Philadelphia Eagles",
    marcVisita: 18,
    Equipo2: 11,
    nomEquipo2: "Washington Comanders",
    marLocal: 28,
  },
  {
    partido: 2,
    idEquipo1: 24,
    nomEquipo1: "Chicago Bears",
    marcVisita: 20,
    Equipo2: 22,
    nomEquipo2: "Green Bay Packers",
    marLocal: 19,
  },
  {
    partido: 3,
    idEquipo1: 32,
    nomEquipo1: "Detroit Lions",
    marcVisita: 6,
    Equipo2: 4,
    nomEquipo2: "Jacksonville Jaguars",
    marLocal: 52,
  },
  {
    partido: 4,
    idEquipo1: 15,
    nomEquipo1: "Tennessee  Titans",
    marcVisita: 13,
    Equipo2: 6,
    nomEquipo2: "Minnesota Vikings",
    marLocal: 23,
  },
  {
    partido: 5,
    idEquipo1: 31,
    nomEquipo1: "Miami Dolphins",
    marcVisita: 6,
    Equipo2: 29,
    nomEquipo2: "Las Vegas Raiders",
    marLocal: 52,
  },
  {
    partido: 6,
    idEquipo1: 10,
    nomEquipo1: "New England Patriots",
    marcVisita: 22,
    Equipo2: 8,
    nomEquipo2: "Los Angeles Rams",
    marLocal: 28,
  },
  {
    partido: 7,
    idEquipo1: 3,
    nomEquipo1: "New Orleans Saints",
    marcVisita: 35,
    Equipo2: 13,
    nomEquipo2: "Cleveland Browns",
    marLocal: 14,
  },
  {
    partido: 8,
    idEquipo1: 7,
    nomEquipo1: "Pittsburgh Steelers",
    marcVisita: 18,
    Equipo2: 30,
    nomEquipo2: "Baltimore Ravens",
    marLocal: 16,
  },
  {
    partido: 9,
    idEquipo1: 5,
    nomEquipo1: "Denver Broncos",
    marcVisita: 38,
    Equipo2: 19,
    nomEquipo2: "Atlanta Falcons",
    marLocal: 6,
  },
  {
    partido: 10,
    idEquipo1: 26,
    nomEquipo1: "San Francisco 49ers",
    marcVisita: 17,
    Equipo2: 16,
    nomEquipo2: "Seattle Seahawks",
    marLocal: 20,
  },
  {
    partido: 11,
    idEquipo1: 14,
    nomEquipo1: "Buffalo Bills",
    marcVisita: 30,
    Equipo2: 12,
    nomEquipo2: "Kansas City Chiefs",
    marLocal: 21,
  },
  {
    partido: 12,
    idEquipo1: 28,
    nomEquipo1: "Los Angeles Chargers",
    marcVisita: 27,
    Equipo2: 2,
    nomEquipo2: "Cincinnati Bengals",
    marLocal: 24,
  },
  {
    partido: 13,
    idEquipo1: 21,
    nomEquipo1: "New York Jets",
    marcVisita: 27,
    Equipo2: 23,
    nomEquipo2: "Indianapolis Colts",
    marLocal: 28,
  },
  {
    partido: 14,
    idEquipo1: 1,
    nomEquipo1: "Dallas Cowboys",
    marcVisita: 10,
    Equipo2: 20,
    nomEquipo2: "Houston Texans",
    marLocal: 34,
  },
];
